### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by psusmit** [alexis-jacq/numpy_ARS#1]
I am not sure about this particular error.I copy-pasted your entire code no import errors are there
this is what i get

(tfgpu) susmit@susmit-Inspiron-3543:~/ARS$ python ars.py 
[2018-09-23 20:15:24,774] Making new env: HalfCheetahBulletEnv-v0
pybullet build time: Sep 23 2018 19:35:09
WalkerBase::__init__ start
[2018-09-23 20:15:24,788] Clearing 4 monitor files from previous run (because force=True was provided)
[2018-09-23 20:15:24,813] Starting new video recorder writing to /home/susmit/ARS/exp/brs/monitor/openaigym.video.0.6679.video000000.mp4
Unknown encoder 'libx264'
Traceback (most recent call last):
  File "ars.py", line 154, in <module>
    train(env, policy, normalizer, hp)
  File "ars.py", line 90, in train
    state, reward, done, _ = env.step(action)
  File "/home/susmit/anaconda3/envs/tfgpu/lib/python3.6/site-packages/gym/core.py", line 103, in step
    return self._step(action)
  File "/home/susmit/anaconda3/envs/tfgpu/lib/python3.6/site-packages/gym/wrappers/monitoring.py", line 34, in _step
    done = self._after_step(observation, reward, done, info)
  File "/home/susmit/anaconda3/envs/tfgpu/lib/python3.6/site-packages/gym/wrappers/monitoring.py", line 184, in _after_step
    self.video_recorder.capture_frame()
  File "/home/susmit/anaconda3/envs/tfgpu/lib/python3.6/site-packages/gym/monitoring/video_recorder.py", line 121, in capture_frame
    self._encode_image_frame(frame)
  File "/home/susmit/anaconda3/envs/tfgpu/lib/python3.6/site-packages/gym/monitoring/video_recorder.py", line 171, in _encode_image_frame
    self.encoder.capture_frame(frame)
  File "/home/susmit/anaconda3/envs/tfgpu/lib/python3.6/site-packages/gym/monitoring/video_recorder.py", line 306, in capture_frame
    self.proc.stdin.write(frame.tobytes())
BrokenPipeError: [Errno 32] Broken pipe
[2018-09-23 20:15:24,893] VideoRecorder encoder exited with status 1
[2018-09-23 20:15:24,894] Finished writing results. You can upload them to the scoreboard via gym.upload('/home/susmit/ARS/exp/brs/monitor')

**Comment by alexis-jacq** [comment]
I have no simple idea for this error. Do you need the video records? otherwise just comment the record line and you should avoid this problem. 

Are you running on your own computer or on some server? it's also possible that you simply have no rights for writing a file. maybe try "sudo python ars.py"

**Comment by psusmit** [comment]
I commented out the record line 
and tried running it with "sudo python ars.py"
i was met with an error:- ImportError: No module named pybullet_envs
but when i ran it with "python ars.py" 
i get this:-  
[2018-09-24 18:28:32,524] Making new env: HalfCheetahBulletEnv-v0
pybullet build time: Sep 23 2018 19:35:09
WalkerBase::__init__ start
episode 0 reward_evaluation -1132.8306537310398
I do not get any error
thank you so much..
